"""The named seams (§4.3). Every port is a Protocol with a real and a fake
implementation; tests inject fakes. This is what makes G6 (test without a
running game) achievable.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Protocol, TypeVar

from ..domain.job import Job
from ..domain.outcome import JobResult

T = TypeVar("T")


class CancelToken(Protocol):
    @property
    def cancelled(self) -> bool: ...


class Handle(Protocol[T]):
    def done(self) -> bool: ...
    def result(self, timeout: float | None = None) -> T: ...


class Executor(Protocol):
    """Same-key submit cancels the in-flight one — v1's generation counters,
    done once. Every UI callback goes through ``on_ui_thread``."""

    def submit(self, key: str, fn: Callable[[CancelToken], T]) -> Any: ...
    def cancel(self, key: str) -> None: ...
    def on_ui_thread(self, fn: Callable[[], None]) -> None: ...
    def shutdown(self) -> None: ...


class BridgeTransport(Protocol):
    """The only thing that knows protocol v3 exists."""

    def submit(self, job: Job) -> str: ...
    def cancel(self, job_id: str) -> bool: ...
    def clear_queue(self) -> int: ...
    def result(self, job_id: str) -> JobResult | None: ...
    def await_result(self, job_id: str, *, timeout: float = 60.0,
                     poll: float = 0.25, on_tick: Any = None) -> JobResult: ...
    def pending_ids(self) -> list[str]: ...
    def claimed_ids(self) -> list[str]: ...
    def queue_depth(self) -> int: ...
    def liveness(self) -> Any: ...
    def sweep_crashed(self) -> list[str]: ...
    def force_drain_snippet(self) -> str: ...
